version: '3.4'

services:

  mongo:
    container_name: bookstoredb
    image: bookstoredb
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - 27018:27017

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

volumes:
  mongodata:
     external: true
         
  
